platform :ios, '9.0'

target 'TTZoomTransitionExample' do
	pod 'TTZoomTransition', :path => '../'

	target 'TTZoomTransitionExampleTests' do
		inherit! :search_paths
		
		pod 'Specta'
		pod 'Expecta'
		pod 'Expecta+Snapshots'
		pod 'OCMock'
	end
end


